language: node_js
node_js: node

script:
- npm run ci

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: npm
  edge: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master
